### ISSUE TITLE
Could not resolve data provider for package 'java.util' when run CQL

### ISSUE THREAD

**Issue by JuliaDawson** [cqframework/ecqm-content-qicore-2022#10]
Zero problems are reported but when CQL is run, it fails with message:
"The following errors were encountered during evaluation:
org.opencsd.cqf.cql.engine.exception.CqlException: Could not resolve data provider for package 'java.util'."
Please see attached CQL, testcases and screenshots.

Maybe unrelated but when VScode is started, a screen pops up saying:
'Folder contains a Dev Container configuration file. Reopen folder to develop in a container (learn more).'
   When click on 'Reopen in Container' it says "Docker version 17.12.0 or later required."
Is the above error related to this? Is Docker required?  We may not have access Docker at this time

Tried starting VSCode within a CMD shell by changing direcotories to where the repository is and then starting VSCode with 'code .' but got the same errors. 

Thanks for all of the help!

[ScreenShotsForJavaUtilnotResolved.zip](https://github.com/cqframework/ecqm-content-qicore-2022/files/9214391/ScreenShotsForJavaUtilnotResolved.zip)
.

**Comment by brynrhodes** [comment]
Fixed in 0.4.0
