### ISSUE TITLE
QICore has a delay before it runs, then runs ok but puts out the following error messages.

### ISSUE THREAD

**Issue by JuliaDawson** [cqframework/ecqm-content-qicore-2022#11]
I re-cloned the repository to get any changes. Code and testcases than ran before still ran, but sometimes hang indefinitely but them run with a normal elapsed time (but sometimes do not run at all). When they do run, the test case output is followed by these error messages:
The following errors were encountered during evaluation:
14:35:44.678 [pool-2-thread-1] INFO  ca.uhn.fhir.util.VersionUtil - HAPI FHIR version 5.6.3 - Rev b54b29145c
14:35:44.678 [pool-2-thread-1] INFO  ca.uhn.fhir.context.FhirContext - Creating new FHIR context for FHIR version [R4]
14:35:48.278 [pool-2-thread-1] INFO  c.u.f.c.support.DefaultProfileValidationSupport - Loading structure definitions from classpath: /org/hl7/fhir/r4/model/profile/profiles-resources.xml
14:35:48.308 [pool-2-thread-1] INFO  ca.uhn.fhir.util.XmlUtil - Unable to determine StAX implementation: java.xml/META-INF/MANIFEST.MF not found
14:35:49.498 [pool-2-thread-1] INFO  c.u.f.c.support.DefaultProfileValidationSupport - Loading structure definitions from classpath: /org/hl7/fhir/r4/model/profile/profiles-types.xml
14:35:49.628 [pool-2-thread-1] INFO  c.u.f.c.support.DefaultProfileValidationSupport - Loading structure definitions from classpath: /org/hl7/fhir/r4/model/profile/profiles-others.xml
14:35:49.928 [pool-2-thread-1] INFO  c.u.f.c.support.DefaultProfileValidationSupport - Loading structure definitions from classpath: /org/hl7/fhir/r4/model/extension/extension-definitions.xml
14:35:50.228 [pool-2-thread-1] INFO  ca.uhn.fhir.context.FhirContext - Creating new FHIR context for FHIR version [R4]

**Comment by brynrhodes** [comment]
Fixed in 0.4.0
