### ISSUE TITLE
FHIRCommon.ToInterval translator error

### ISSUE THREAD

**Issue by drthyl** [cqframework/ecqm-content-qicore-2022#5]
There is a translator error with the invocation of FHIRCommon."ToInterval" in a CQL file using QICore version 4.1.1. Please see error screenshots from the VS Code CQL Plugin environment below and a zip folder (with example CQL file and test case).
https://github.com/cqframework/ecqm-content-qicore-2022/blob/0dd7ab0d0af8be17d04575c1c5d1d1f9bfaf76f3/input/cql/FHIRCommon.cql#L118-L138
[Example.zip](https://github.com/cqframework/ecqm-content-qicore-2022/files/8993230/Example.zip)
![image](https://user-images.githubusercontent.com/82893468/175698025-5ed25ce6-09c1-4a2d-91fb-5ae529db46f7.png)
![image](https://user-images.githubusercontent.com/82893468/175698017-19ca816a-72e3-4b68-940d-c4188c1d60ec.png)

**Comment by drthyl** [comment]
Thanks @JuliaDawson ! Would you mind re-opening this issue? I don't think this issue will be resolved until the translator fix, per https://github.com/cqframework/ecqm-content-qicore-2022/pull/7. The QICoreCommon library is a workaround for the time being. Thank you!

**Comment by JuliaDawson** [comment]
Sorry about this, thought I was closing my above comment.

**Comment by brynrhodes** [comment]
This issue is resolved with the latest plugin
